config/routes.rb
Rails.application.routes.draw do
 
  mount RailsAdmin::Engine => '/superadmin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'theaters#index'
  get 'bookings/index'

  namespace :admin do
    root 'screens#index'
    resources :screens, :shows, :bookings
  end
     
  resources :theaters do
    resources :shows
      resources :bookings
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #

      user ||= User.new # guest user (not logged in)
      if user.role == 1
            can :manage, :all
            can :access, :rails_admin
            can :       
      end
      if user.role == 2
            can :manage, User
            can :access, :rails_admin       
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
  belongs_to :movie
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :show
  belongs_to :user

  validates :is_confirm, :seats, :amount, presence: true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :theaters
  has_one_attached :image

  validates :name, :state, presence:true
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :name, presence: true

  has_many :assets
  has_one_attached :image
  has_many :shows

  validates :name, :language, :category, :description, :runtime, :release_date, presence: true
end

app/models/screen.rb
class Screen < ApplicationRecord
  belongs_to :theater
  has_many :shows

  validates :name, :seats, presence: true
end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :movie
  belongs_to :screen
  has_many :bookings

  validates :date, :time, :amount ,presence: true
  validates :screen_id, presence: { message: "Can't be empty"}, acceptance: { message: 'must be abided' }
  validates :movie_id, presence: true, numericality: { message: "Must provide" }
end

app/models/theater.rb
class Theater < ApplicationRecord
  belongs_to :city
  has_one_attached :image
  has_many :screens
  has_many :theater_admins

  validates :name, :pincode, presence: true
end

app/models/theater_admin.rb
class TheaterAdmin < ApplicationRecord
  belongs_to :theater
  belongs_to :user

  validates :theater_id, :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :bookings

         validates :name, :email, :password, :city, :role, :phone, presence: true

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.create(booking_params)
    if @booking.save
      render :index
    end
  end


  def booking_params
    params.require(:booking).permit(:show_id, :user_id, :is_confirm, :seats ,:amount)
  end

end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  def index
    @theater = Theater.find(params[:theater_id])
    @screens = @theater.screens
  end

  def show
    @theater = Theater.find(params[:theater_id])
    @show = Show.find(params[:id])
    @booking = Booking.new
    @booking_seat = []
    @show.bookings.each do |s|
      @booking_seat += s.seats.split(",").to_a.map(&:to_i)
    end
    @booking = Booking.new
  end

end

app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
  def index
    @theaters = Theater.all
    @cities = City.all
  end

  def show
    @theater = Theater.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/screens_helper.rb
module ScreensHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/theater_admin_helper.rb
module TheaterAdminHelper
end

app/helpers/theaters_helper.rb
module TheatersHelper
end

app/views/admin/_sidebar.html.slim
<div class="row">
    <div class="col-sm-3">
      -if @theater.image.attached?
        = image_tag @theater.image, style:"height:200px;width:200px; "
      -else
        = 0 
      h3= @theater.name
      <ul class="nav nav-pills flex-column">
        <li class="nav-item">
          = link_to "Screens", admin_screens_path, class: "btn btn-warning nav-link  "
        </li>
        <li class="nav-item">
          = link_to "Shows", admin_shows_path, class: "btn btn-warning nav-link"
        </li>
        <li class="nav-item">
          = link_to "Bookings", admin_bookings_path, class: "btn btn-warning nav-link  "
        </li>
      </ul>
      <hr class="d-sm-none">
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookmymovie</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Raleway:300,400,500,700,800" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        
        <div>
        <a href="/" class="pull-left">
        <%= image_tag "—Pngtree—record board the film movie_3940116.png",style:"width: 70px; height:90px" %>
        <a class="navbar-brand" href='/'>BookmyMovie</a>
        </div>
    
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>


        <div>
            <% if user_signed_in? %>
            <% if current_user.role == 2 %>
                <a href="<%= admin_root_path %>" class="btn btn-warning me-2">Manage Theater</a>
            <% end %>
            <% if current_user.role == 1 %>
                <a href="<%= rails_admin_path %>" class="btn btn-warning me-2">Manage all</a>
            <% end %>
              <%= link_to current_user.name, edit_user_registration_path, :class => 'btn btn-warning' %> 	&nbsp;	&nbsp;
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-warning'  %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => 'btn btn-warning'  %> &nbsp;	 &nbsp;
              <%= link_to "Login", new_user_session_path, :class => 'btn btn-warning'  %>
            <% end %>

        </div>
      </div>    
    </nav>

    <div class="container">
    <div>
    <p></p><div>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>