config/routes.rb
Rails.application.routes.draw do
 
  mount RailsAdmin::Engine => '/superadmin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'theaters#index'
  get 'bookings/index'

  namespace :admin do
    root 'screens#index'
    resources :screens, :shows, :bookings
  end
     
  resources :theaters do
    resources :shows
      resources :bookings
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #

      user ||= User.new # guest user (not logged in)
      if user.role == 1
            can :manage, :all
            can :access, :rails_admin
            can :       
      end
      if user.role == 2
            can :manage, User
            can :access, :rails_admin       
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
  belongs_to :movie
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :show
  belongs_to :user

  validates :is_confirm, :seats, :amount, presence: true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :theaters
  has_one_attached :image

  validates :name, :state, presence:true
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :name, presence: true

  has_many :assets
  has_one_attached :image
  has_many :shows

  validates :name, :language, :category, :description, :runtime, :release_date, presence: true
end

app/models/screen.rb
class Screen < ApplicationRecord
  belongs_to :theater
  has_many :shows

  validates :name, :seats, presence: true
end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :movie
  belongs_to :screen
  has_many :bookings

  validates :date, :time, :amount ,presence: true
  validates :screen_id, presence: { message: "Can't be empty"}, acceptance: { message: 'must be abided' }
  validates :movie_id, presence: true, numericality: { message: "Must provide" }
end

app/models/theater.rb
class Theater < ApplicationRecord
  belongs_to :city
  has_one_attached :image
  has_many :screens
  has_many :theater_admins

  validates :name, :pincode, presence: true
end

app/models/theater_admin.rb
class TheaterAdmin < ApplicationRecord
  belongs_to :theater
  belongs_to :user

  validates :theater_id, :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :bookings

         validates :name, :email, :password, :city, :role, :phone, presence: true

end

app/controllers/admin/screens_controller.rb
class Admin::ScreensController < ApplicationController
  before_action :template

  def template
    @theateradmin = TheaterAdmin.where(user: current_user).first
    @theater = @theateradmin.theater
  end

  def index 
    if @theateradmin.nil?
      redirect_to root_path
    else
      @theater = @theateradmin.theater
      @screens = @theater.screens
    end
    @screen = Screen.new
  end

  def create
    @screen = Screen.create(screen_params)
    if @screen.save
      redirect_to admin_screens_path
    else
      flash.now[:messages] = @screen.errors.full_messages[0]
      render :index
    end
  end

  def edit
    @screen = @theater.screens.find(params[:id])
  end

  def update
    @screen = @theater.screens.find(params[:id])
    if @screen.update(screen_params)
      redirect_to admin_screens_path
    end
  end

  def destroy
    @screen = @theater.screens.find(params[:id])
    if @screen.destroy
      redirect_to admin_screens_path
    end
  end

  def screen_params
    params.require(:screen).permit(:name, :seats, :theater_id)
  end
end

app/controllers/admin/shows_controller.rb
class Admin::ShowsController < ApplicationController
  def index
    @theateradmin = TheaterAdmin.where(user: current_user).first
    @theater = @theateradmin.theater
    @screens = @theater.screens
    @show = Show.new
  end

  def create
    @theateradmin = TheaterAdmin.where(user: current_user).first
    @theater = @theateradmin.theater
    @show = Show.create(show_params)
    if @show.save
      redirect_to admin_shows_path
    else
      flash.now[:messages] = @show.errors.full_messages[0]
      render :index
    end
  end

  def edit
    @show = Show.find(params[:id])
  end

  def update
    @show = Show.find(params[:id])
    if @show.update(show_params)
      redirect_to admin_shows_path
    end
  end

  def destroy
    @show = Show.find(params[:id])
    if @show.destroy
      redirect_to admin_shows_path
    end
  end

  def show_params
    params.require(:show).permit(:movie_id, :screen_id, :date, :amount, :time)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:city,:phone])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.create(booking_params)
    if @booking.save
      render :index
    end
  end


  def booking_params
    params.require(:booking).permit(:show_id, :user_id, :is_confirm, :seats ,:amount)
  end

end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  def index
    @theater = Theater.find(params[:theater_id])
    @screens = @theater.screens
  end

  def show
    @theater = Theater.find(params[:theater_id])
    @show = Show.find(params[:id])
    @booking = Booking.new
    @booking_seat = []
    @show.bookings.each do |s|
      @booking_seat += s.seats.split(",").to_a.map(&:to_i)
    end
    @booking = Booking.new
  end

end

app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
  def index
    @theaters = Theater.all
    @cities = City.all
  end

  def show
    @theater = Theater.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/screens_helper.rb
module ScreensHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/theater_admin_helper.rb
module TheaterAdminHelper
end

app/helpers/theaters_helper.rb
module TheatersHelper
end

app/views/admin/screens/edit.html.slim
div class="card" style="width:72rem; text-align: center; "
  div class="card-body" style="width:70rem; position: center;"
  h1 Screen Edit
  =form_for @screen ,url:admin_screen_path(@screen.id) do |f|
    div class="mb-3"
      = f.text_field :name, class: "form-control col-6", placeholder: "Enter Screen"
    div class="mb-3"
      = f.text_field :seats, class: "form-control col-12", placeholder: "Seats"
    div class="mb-3"   
      = f.button :submit, :class => "btn btn-warning"

app/views/admin/screens/index.html.slim
div class="card" style="width:72rem; text-align: center;"
  div class="card-body" style="width:70rem; position: center;"
  h1 #{current_user.name} Panel
  div class="row"
  =render '/admin/sidebar'
  div class="col-9"
    table.table
      thead
        tr
          th scope="col" ID
          th scope="col" Screen Name
          th scope="col" Seats     
          th scope="col" city
          th scope="col" Edit
          th scope="col" Delete
      tbody
        - @theater.screens.each do |f|
            tr
              td = f.id
              td = f.name
              td = f.seats
              td = @theater.city.name
              td = link_to "",edit_admin_screen_path(f.id), method: 'GET',class:"far fa-edit"
              td = link_to "",admin_screen_path(f.id), method: 'DELETE',class:"fas fa-trash"
    div class="card" style="width:50rem; text-align: center;"
    h2 = "Add Screen"
    =form_for @screen, url: admin_screens_path() do |s|
      div class="mb-3"
        = s.text_field :name, class: "form-control col-12", placeholder: "Enter Screen Name"
      div class="mb-3"
        = s.text_field :seats, class: "form-control col-12", placeholder: "Seats"
      div class="mb-3"
        = s.hidden_field :theater_id, value: @theater.id
        = s.button :submit, class: "btn btn-warning"
      -if flash[:messages]
        =flash[:messages]
      end
            

app/views/theaters/index.html.slim
div class="card-body " style="width:70rem; position: center; "
  <marquee>
  <h3><font family="TimesNewRoman" color="dark violet"><b>Welcome to BookMyMovie!! Happy Watching!!</b></font></h3> </marquee>

  div class="card" style="width:70rem; text-align: center; "
    div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel"
      div class="carousel-indicators"
        button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"
        button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"
        button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"
      div class="carousel-inner",style="box-shadow: 0px 20px 50px #555;"
          div class="carousel-item active"
            = image_tag "uriBaner.jpeg", class:"d-block w-100"  
          div class="carousel-item"
            = image_tag "tanhajiBAner.jpeg", class:"d-block w-100"
          div class="carousel-item"
            = image_tag "GolmalBAner.jpg", class:"d-block w-100" 
          button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev"
            span class="carousel-control-prev-icon" aria-hidden="true"
            span class="visually-hidden" Previous
          button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next"
            span class="carousel-control-next-icon" aria-hidden="true"
            span class="visually-hidden" Next
br
h3 Theaters
div class="card" style="width:68rem; text-align: center; "
  div class="card-body " style="width:68rem; position: center; box-shadow: 0px 20px 50px #555;"
    div class="row"
      - @theaters.each do |f|
        div class="col-3" style="margin-top: 50px; text-shadow: 4px 2px 2px 4px #000000;"
          div class="card"
            -if f.image.attached?
              = image_tag f.image, class:"card-img-top", style:"height:300px;width:auto;"
            -else
              = 0
          div class="card-body"
          h4 = f.name
          = link_to "Theater Details", theater_path(f), class: "btn btn-warning"

      
    

  

app/views/theaters/screens.html.slim
<div class="card" style="width:70rem; text-align: center; ">
<div class="card-body " style="width:70rem; position: center; ">

div class="row"
  - @screens.each do |f|
    br
    - f.shows.each do |m|
      h2 = f.name
      div class="card"
        div class="card-body item-align-center"
          -if m.movie.image.attached?
            = image_tag m.movie.image, style:"height:200px;width:200px; "
          -else
            = 0
        h4= m.movie.name
        div
        = "Date: #{m.date.strftime("%B %-d, %Y")}"  
        div
        = "Time: #{m.time.strftime("%I:%M %p")}"
        div
        = "Language: #{m.movie.language}"  
        div
        = "Runtime: #{m.movie.runtime} mins"  

        = link_to "Book @#{m.amonut} Rs", '#' ,class:"btn btn-warning"

          

app/views/theaters/show.html.slim
<div class="card" style="width:70rem; text-align: center; ">
<div class="card-body " style="width:70rem; position: center; ">

div class="row"
 
div class="card"
div class="card-body item-align-center"
  -if @theater.image.attached?
    = image_tag @theater.image, style:"height:200px;width:200px; "
  -else
    = 0
h4= @theater.name
div
= "City: #{@theater.city.name}"  
div
= "Pincode: #{@theater.pincode}"
div  
= link_to "See Available Shows", theater_shows_path(@theater.id) ,class:"btn btn-warning"

      