config/routes.rb
Rails.application.routes.draw do
 
  mount RailsAdmin::Engine => '/superadmin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'theaters#index'
  get 'bookings/index'

  namespace :admin do
    root 'screens#index'
    resources :screens, :shows, :bookings
  end
     
  resources :theaters do
    resources :shows
      resources :bookings
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #

      user ||= User.new # guest user (not logged in)
      if user.role == 1
            can :manage, :all
            can :access, :rails_admin
            can :       
      end
      if user.role == 2
            can :manage, User
            can :access, :rails_admin       
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
  belongs_to :movie
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :show
  belongs_to :user

  validates :is_confirm, :seats, :amount, presence: true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :theaters
  has_one_attached :image

  validates :name, :state, presence:true
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :name, presence: true

  has_many :assets
  has_one_attached :image
  has_many :shows

  validates :name, :language, :category, :description, :runtime, :release_date, presence: true
end

app/models/screen.rb
class Screen < ApplicationRecord
  belongs_to :theater
  has_many :shows

  validates :name, :seats, presence: true
end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :movie
  belongs_to :screen
  has_many :bookings

  validates :date, :time, :amount ,presence: true
  validates :screen_id, presence: { message: "Can't be empty"}, acceptance: { message: 'must be abided' }
  validates :movie_id, presence: true, numericality: { message: "Must provide" }
end

app/models/theater.rb
class Theater < ApplicationRecord
  belongs_to :city
  has_one_attached :image
  has_many :screens
  has_many :theater_admins

  validates :name, :pincode, presence: true
end

app/models/theater_admin.rb
class TheaterAdmin < ApplicationRecord
  belongs_to :theater
  belongs_to :user

  validates :theater_id, :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :bookings

         validates :name, :email, :password, :city, :role, :phone, presence: true

end

app/controllers/admin/bookings_controller.rb
class Admin::BookingsController < ApplicationController
  def index
    @theateradmin = TheaterAdmin.where(user: current_user).first
    @theater = @theateradmin.theater
    @screens = @theater.screens
  end

end

app/controllers/admin/screens_controller.rb
class Admin::ScreensController < ApplicationController
  before_action :template

  def template
    @theateradmin = TheaterAdmin.where(user: current_user).first
    @theater = @theateradmin.theater
  end

  def index 
    if @theateradmin.nil?
      redirect_to root_path
    else
      @theater = @theateradmin.theater
      @screens = @theater.screens
    end
    @screen = Screen.new
  end

  def create
    @screen = Screen.create(screen_params)
    if @screen.save
      redirect_to admin_screens_path
    else
      flash.now[:messages] = @screen.errors.full_messages[0]
      render :index
    end
  end

  def edit
    @screen = @theater.screens.find(params[:id])
  end

  def update
    @screen = @theater.screens.find(params[:id])
    if @screen.update(screen_params)
      redirect_to admin_screens_path
    end
  end

  def destroy
    @screen = @theater.screens.find(params[:id])
    if @screen.destroy
      redirect_to admin_screens_path
    end
  end

  def screen_params
    params.require(:screen).permit(:name, :seats, :theater_id)
  end
end

app/controllers/admin/shows_controller.rb
class Admin::ShowsController < ApplicationController
  def index
    @theateradmin = TheaterAdmin.where(user: current_user).first
    @theater = @theateradmin.theater
    @screens = @theater.screens
    @show = Show.new
  end

  def create
    @theateradmin = TheaterAdmin.where(user: current_user).first
    @theater = @theateradmin.theater
    @show = Show.create(show_params)
    if @show.save
      redirect_to admin_shows_path
    else
      flash.now[:messages] = @show.errors.full_messages[0]
      render :index
    end
  end

  def edit
    @show = Show.find(params[:id])
  end

  def update
    @show = Show.find(params[:id])
    if @show.update(show_params)
      redirect_to admin_shows_path
    end
  end

  def destroy
    @show = Show.find(params[:id])
    if @show.destroy
      redirect_to admin_shows_path
    end
  end

  def show_params
    params.require(:show).permit(:movie_id, :screen_id, :date, :amount, :time)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:city,:phone])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.create(booking_params)
    if @booking.save
      render :index
    end
  end


  def booking_params
    params.require(:booking).permit(:show_id, :user_id, :is_confirm, :seats ,:amount)
  end

end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  def index
    @theater = Theater.find(params[:theater_id])
    @screens = @theater.screens
  end

  def show
    @theater = Theater.find(params[:theater_id])
    @show = Show.find(params[:id])
    @booking = Booking.new
    @booking_seat = []
    @show.bookings.each do |s|
      @booking_seat += s.seats.split(",").to_a.map(&:to_i)
    end
    @booking = Booking.new
  end

end

app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
  def index
    @theaters = Theater.all
    @cities = City.all
  end

  def show
    @theater = Theater.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/screens_helper.rb
module ScreensHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/theater_admin_helper.rb
module TheaterAdminHelper
end

app/helpers/theaters_helper.rb
module TheatersHelper
end

app/views/admin/bookings/index.html.slim
div class="card" style="width:72rem; text-align: center; "
  div class="card-body" style="width:70rem; position: center;"
  h3 Bookings
  div class="row"
  =render '/admin/sidebar'
  div class="col-9"
    table.table
      thead
        tr
          th scope="col" Movie Name
          th scope="col" User Name
          th scope="col" Seats
          th scope="col" Status     
      tbody
        -@screens.each do |f|
          -f.shows.each do |s|
            -s.bookings.each do |b|
              tr
                td= b.show.movie.name
                td= b.user.name
                td= b.seats
                td 
                  -if b.is_confirm = true
                    = "Successful"
      
              

              


          
            

app/views/admin/shows/edit.html.slim
div class="card" style="width:72rem; text-align: center; "
  div class="card-body" style="width:70rem; position: center;"
  h3 Edit Shows
  div
    = form_for @show, url:admin_show_path(@show.id) do |f|
      = f.label :screen_id
      = f.text_field :screen_id
      br
      br
      = f.label :movie_id
      = f.text_field :movie_id
      br
      br
      = f.label :date
      = f.date_field :date
      br
      br
      = f.label :time 
      = f.time_field :time
      br
      br
      = f.label :amount
      = f.text_field :amount
      br
      = f.button :Update, :class => "btn btn-warning"

      

      

app/views/admin/shows/index.html.slim
div class="card" style="width:72rem; text-align: center; "
  div class="card-body" style="width:70rem; position: center;"
  h1 Shows
  div class="row"
  =render '/admin/sidebar'
  div class="col-9"
    table.table 
      thead
        tr
          th scope="col" Name
          th scope="col" Screen
          th scope="col" Date
          th scope="col" Time 
          th scope="col" Runtime
          th scope="col" Amount
          th scope="col" Edit
          th scope="col" Delete
      tbody 
        -@theater.screens.each do |s|
          -s.shows.each do |m|
            tr
              td= m.movie.name 
              td= m.screen.name
              td= m.date
              td= m.time 
              td= m.movie.runtime 
              td= m.amount
              td= link_to "",edit_admin_show_path(m),method:"GET",class:"fas fa-edit"
              td= link_to "",admin_show_path(m),method:"DELETE",class:"fas fa-trash-alt"
    div class="card" style="width:50rem; text-align: center; "
    h3 Add Shows
    = form_for @show, url:admin_shows_path() do |f|
      = f.label :screen_id
      = f.text_field :screen_id
      br
      br
      = f.label :movie_id
      = f.text_field :movie_id
      br
      br
      = f.label :date
      = f.text_field :date
      br
      br
      = f.label :time 
      = f.text_field :time
      br
      br
      = f.label :amount
      = f.text_field :amount
      div class="mb-3" 
        = f.button :submit, :class => "btn btn-warning"
      -if flash[:messages]
        =flash[:messages]
      end

app/views/admin/shows/show.html.slim
div class="card" style="width:70rem; text-align: center; "
  div class="card-body " style="width:70rem; position: center; "

div class="row"
      h2 = @show.movie.name
      div class="card"
        div class="card-body item-align-center"
          -if @show.movie.image.attached?
            = image_tag @show.movie.image, style:"height:200px;width:200px; "
          -else
            = 0
        h4= @show.movie.name
        div
        = "Show Date: #{@show.date.strftime("%B %-d, %Y")}"  
        div
        = "Show Time: #{@show.time.strftime("%I:%M %p")}"
        div
        = "Language: #{@show.movie.language}"  
        div
        = "Runtime: #{@show.movie.runtime} mins"  

        = link_to "Book @#{@show.amount} Rs", seat_path ,class:"btn btn-warning"

          






        
        
        
        

          

app/views/bookings/index.html.slim
div class="card" style="hover;width:70rem; text-align: center; "
  div class="card-body" style="width:70rem; position: center; "
    div class="card-body " style="width:68rem; position: center; "
    h1 You have Successfully Booked The Seats 
    = image_tag "green-tick.png", style:"width:10rem;"
    h4 Thank You Visit Again..
    = link_to "Home Page",theaters_path,class:"btn btn-warning"

app/views/shows/index.html.slim
<div class="card" style="width:70rem; text-align: center; ">
<div class="card-body " style="width:70rem; position: center; ">

div class="row"
  - @screens.each do |f|
    br
    - f.shows.each do |m|
      h2 = f.name
      div class="card"
        div class="card-body item-align-center"
          -if m.movie.image.attached?
            = image_tag m.movie.image, style:"height:200px;width:200px; "
          -else
            = 0
        h4= m.movie.name

        = link_to "Book @#{m.amount} Rs", theater_show_path(@theater,m) ,class:"btn btn-warning"


          